/var/spool/slurm//job93422/slurm_script: line 17: cd: packnet-sfm: No such file or directory
[I 05:08:40.144 LabApp] JupyterLab extension loaded from /softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/jupyterlab
[I 05:08:40.144 LabApp] JupyterLab application directory is /softs/anaconda/4.9.3/python3.8/share/jupyter/lab
[I 05:08:40.175 LabApp] Serving notebooks from local directory: /home/users/vbelissen/packnet-sfm
[I 05:08:40.175 LabApp] Jupyter Notebook 6.1.4 is running at:
[I 05:08:40.175 LabApp] http://node15:8888/?token=11deb18df063fd9baec56af3672a79f97fd1d6d8740589fe
[I 05:08:40.175 LabApp]  or http://127.0.0.1:8888/?token=11deb18df063fd9baec56af3672a79f97fd1d6d8740589fe
[I 05:08:40.175 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 05:08:40.192 LabApp] No web browser found: could not locate runnable browser.
[C 05:08:40.192 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/users/vbelissen/.local/share/jupyter/runtime/nbserver-36054-open.html
    Or copy and paste one of these URLs:
        http://node15:8888/?token=11deb18df063fd9baec56af3672a79f97fd1d6d8740589fe
     or http://127.0.0.1:8888/?token=11deb18df063fd9baec56af3672a79f97fd1d6d8740589fe
[W 08:54:35.270 LabApp] 404 GET /terminals/websocket/2 (10.6.0.1) 733.51ms referer=None
[W 08:54:37.768 LabApp] 404 GET /terminals/websocket/1 (10.6.0.1) 2.51ms referer=None
[W 08:55:30.801 LabApp] Could not determine jupyterlab build status without nodejs
[W 08:55:50.626 LabApp] 404 GET /terminals/websocket/1 (10.6.0.1) 6.57ms referer=None
[W 08:55:50.919 LabApp] 404 GET /terminals/websocket/2 (10.6.0.1) 2.97ms referer=None
[W 08:55:51.363 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 2.55ms referer=None
[W 08:56:09.036 LabApp] 404 GET /terminals/websocket/1 (10.6.0.1) 2.99ms referer=None
[W 08:56:09.992 LabApp] 404 GET /terminals/websocket/2 (10.6.0.1) 2.62ms referer=None
[W 08:56:11.458 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 2.45ms referer=None
[W 08:56:14.609 LabApp] 404 GET /terminals/websocket/1 (10.6.0.1) 2.78ms referer=None
[W 08:56:17.823 LabApp] 404 GET /terminals/websocket/2 (10.6.0.1) 2.46ms referer=None
[W 08:56:18.483 LabApp] Could not determine jupyterlab build status without nodejs
[I 09:05:30.979 LabApp] New terminal with automatic name: 1
[I 09:05:34.197 LabApp] New terminal with automatic name: 2
TermSocket.open: 1
TermSocket.open: Opened 1
TermSocket.open: 2
TermSocket.open: Opened 2
[I 12:26:32.670 LabApp] Copying configs/fisheye_v2_config33.yaml to /configs
[I 12:26:49.952 LabApp] Saving file at /configs/fisheye_v2_config33-001.yaml
Websocket closed
Websocket closed
[W 06:10:48.318 LabApp] Could not determine jupyterlab build status without nodejs
TermSocket.open: 1
TermSocket.open: Opened 1
TermSocket.open: 2
TermSocket.open: Opened 2
[W 06:33:50.803 LabApp] WebSocket ping timeout after 119991 ms.
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
[W 06:33:52.001 LabApp] WebSocket ping timeout after 119893 ms.
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(14, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(14, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(14, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(14, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
Websocket closed
TermSocket.open: 2
TermSocket.open: Opened 2
TermSocket.open: 1
TermSocket.open: Opened 1
Websocket closed
Websocket closed
TermSocket.open: 1
TermSocket.open: Opened 1
Websocket closed
[W 07:59:05.033 LabApp] Could not determine jupyterlab build status without nodejs
TermSocket.open: 1
TermSocket.open: Opened 1
TermSocket.open: 2
TermSocket.open: Opened 2
[W 07:59:06.489 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 7.04ms referer=None
[W 07:59:08.162 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 1.29ms referer=None
[W 07:59:09.163 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 1.50ms referer=None
[W 07:59:11.811 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 1.42ms referer=None
[W 07:59:17.647 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 1.75ms referer=None
[W 07:59:20.653 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 2.22ms referer=None
[W 07:59:37.579 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 1.75ms referer=None
[W 08:00:32.976 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 15.85ms referer=None
[W 18:29:06.327 LabApp] WebSocket ping timeout after 119991 ms.
[W 18:29:06.439 LabApp] WebSocket ping timeout after 119989 ms.
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
Websocket closed
[W 20:58:37.778 LabApp] Could not determine jupyterlab build status without nodejs
TermSocket.open: 1
TermSocket.open: Opened 1
TermSocket.open: 2
TermSocket.open: Opened 2
[W 20:58:40.593 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 6.41ms referer=None
[W 20:58:42.284 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 2.76ms referer=None
[W 20:58:44.365 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 2.34ms referer=None
[W 20:58:47.920 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 2.84ms referer=None
[W 20:58:53.106 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 3.12ms referer=None
[W 20:58:58.966 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 3.21ms referer=None
[W 20:59:28.677 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 7.47ms referer=None
[W 20:59:37.864 LabApp] 404 GET /terminals/websocket/3 (10.6.0.1) 3.06ms referer=None
[I 21:11:11.491 LabApp] Copying configs/fisheye_v2_config50.yaml to /configs
[I 21:11:26.656 LabApp] Saving file at /configs/fisheye_v2_config51.yaml
[W 22:13:39.641 LabApp] WebSocket ping timeout after 119991 ms.
[W 22:13:39.884 LabApp] WebSocket ping timeout after 119991 ms.
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(14, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(14, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(14, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(14, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(14, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(14, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(14, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(14, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(14, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(14, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(12, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(12, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
Exception in callback BaseAsyncIOLoop._handle_events(14, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(14, 1)>
Traceback (most recent call last):
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/notebook/terminal/handlers.py", line 43, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/softs/anaconda/4.9.3/python3.8/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
[W 09:08:13.443 LabApp] Could not determine jupyterlab build status without nodejs
TermSocket.open: 1
TermSocket.open: Opened 1
TermSocket.open: 2
TermSocket.open: Opened 2
